[package]
name = "juno"
version = "0.1.0"
edition = "2021"
description = "Juno Proxy Server"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
codegen-units = 1
lto = true
strip = true
